spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev#开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.32.102:3306/ztesoft03
    max-active: 100
    maxPoolSize: 100
    minPoolSize: 5
    max-idle: 60
    max-maxWait: 100
    min-idle: 8
    initial-size: 20
    acquireIncrement: 5
    maxStatements: 5
    idleConnectionTestPeriod: 60
    #是否在自动回收超时连接的时候打印连接的超时错误
    log-abandoned: true
    #是否自动回收超时连接
    remove-abandoned: true
    #超时时间(以秒数为单位)
    remove-abandoned-timeout: 180
    ##<!-- 超时等待时间以毫秒为单位 6000毫秒/1000等于60秒 -->
    max-wait: 10000
    test-while-idle: true
    #检测数据库的查询语句
    validation-query: select 1 from dual
    test-on-borrow: true
    #每隔五分钟检测空闲超过10分钟的连接
    min-evictable-idle-time-millis: 600000
    time-between-eviction-runs-millis: 300000
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ztesoft.springcloud.dto
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client: #将客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: ztesoft-microservicecloud-springcloudconfig01
  company.name: www.ztesoft.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test  # 测试环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.32.102:3306/ztesoft02
    max-active: 100
    maxPoolSize: 100
    minPoolSize: 5
    max-idle: 60
    max-maxWait: 100
    min-idle: 8
    initial-size: 20
    acquireIncrement: 5
    maxStatements: 5
    idleConnectionTestPeriod: 60
    #是否在自动回收超时连接的时候打印连接的超时错误
    log-abandoned: true
    #是否自动回收超时连接
    remove-abandoned: true
    #超时时间(以秒数为单位)
    remove-abandoned-timeout: 180
    ##<!-- 超时等待时间以毫秒为单位 6000毫秒/1000等于60秒 -->
    max-wait: 10000
    test-while-idle: true
    #检测数据库的查询语句
    validation-query: select 1 from dual
    test-on-borrow: true
    #每隔五分钟检测空闲超过10分钟的连接
    min-evictable-idle-time-millis: 600000
    time-between-eviction-runs-millis: 300000
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ztesoft.springcloud.dto
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client: #将客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: ztesoft-microservicecloud-springcloudconfig01
  company.name: www.ztesoft.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$